export const allTextureKeys = {
	shipBlue: 'shipBlue',
	shipBlue2: 'shipBlue2',
	bomb: 'bomb',
	musicOn: 'musicOn',
	musicOff: 'musicOff',
	effectsOn: 'effectsOn',
	effectsOff: 'effectsOff',
	enemyShip: 'enemyShip',
	man: 'man',
	man2: 'man2',
	woman: 'woman',
	TombStone1: 'TombStone1',
	TombStone2: 'TombStone2',
	spaceShip: 'spaceShip',
	bullet1: 'bullet1',
	bullet2: 'bullet2',
	explosion: 'explosion',
	explosion1: 'explosion1',
	explosion2: 'explosion2',
	explosion3: 'explosion3',
	background1: 'background1',
	background2: 'background2',
	background3: 'background3',
	background4: 'background4',
	background5: 'background5',
	background6: 'background6',
	background7: 'background7',
	background8: 'background8',
	background9: 'background9',
	background10: 'background10',
} as const;

const appTextures: Record<string, string> = {
	[allTextureKeys.shipBlue]: '/game/sprites/enemy/shipBlue.png',
	[allTextureKeys.shipBlue2]: '/game/sprites/enemy/shipBlue2.png',
	[allTextureKeys.bomb]: '/game/sprites/bomb.png',
	[allTextureKeys.musicOn]: '/game/sprites/ui/music_on.png',
	[allTextureKeys.musicOff]: '/game/sprites/ui/music_off.png',
	[allTextureKeys.effectsOn]: '/game/sprites/ui/volume_on.png',
	[allTextureKeys.effectsOff]: '/game/sprites/ui/volume_off.png',
	[allTextureKeys.enemyShip]: '/game/sprites/enemy/shipBlue.png',
	[allTextureKeys.man]: '/game/sprites/people/man.png',
	[allTextureKeys.man2]: '/game/sprites/people/man2.png',
	[allTextureKeys.woman]: '/game/sprites/people/woman.png',
	[allTextureKeys.TombStone1]: '/game/sprites/people/TombStone1.png',
	[allTextureKeys.TombStone2]: '/game/sprites/people/TombStone2.png',
	[allTextureKeys.spaceShip]: '/game/sprites/player.png',
	[allTextureKeys.bullet1]: '/game/sprites/bullets/bullet1.json',
	[allTextureKeys.bullet2]: '/game/sprites/bullets/bullet2.json',
	[allTextureKeys.explosion]: '/game/sprites/explosion/explosion.json',
	[allTextureKeys.explosion1]: '/game/sprites/explosion/explosion1.json',
	[allTextureKeys.explosion2]: '/game/sprites/explosion/explosion2.json',
	[allTextureKeys.explosion3]: '/game/sprites/explosion/explosion3.json',
	[allTextureKeys.background1]: '/game/backgrounds/background1.png',
	[allTextureKeys.background2]: '/game/backgrounds/background2.png',
	[allTextureKeys.background3]: '/game/backgrounds/background3.png',
	[allTextureKeys.background4]: '/game/backgrounds/background4.png',
	[allTextureKeys.background5]: '/game/backgrounds/background5.png',
	[allTextureKeys.background6]: '/game/backgrounds/background6.png',
	[allTextureKeys.background7]: '/game/backgrounds/background7.png',
	[allTextureKeys.background8]: '/game/backgrounds/background8.png',
	[allTextureKeys.background9]: '/game/backgrounds/background9.png',
	[allTextureKeys.background10]: '/game/backgrounds/background10.png',
};

export default appTextures;
